# model_name_or_path: /home/toolkit/snapshots/fa0277d307db882ff9735fe0edc03cfb24a59442/dpo_pythia410m_tldr
wandb_run_id: snow
gold_model_name: cleanrl/EleutherAI_pythia-6.9b-deduped__reward__tldr
gold_tokenizer_name: EleutherAI/pythia-6.9b-deduped
eval_batch_size: 8
eval_dtype: float16
